### ISSUE TITLE
🐛 [BUG] - Showing list of Repository have some exception

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_client#177]
### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

### Description

![image](https://github.com/AgainIoT/Open-Set-Go_client/assets/77202633/cf21418f-d0c0-4fc9-a6fa-4eb176fa8e57)

If OWNER is selected and F5 is pressed, as in the corresponding screen, OWNER is already selected, but REPOSITORY data is lost. Therefore, in order to solve this problem, it seems that OWNER can be selected again by pressing F5. Of course, PERSIST RECOIL can be used to prevent REPOSITORY LIST's data from flying away, but this could cause problems in getting REPO to be selected again, so you'll have to pay attention to a number of things!
만약 해당 화면과 같이, OWNER를 선택하고, F5를 누르면, OWNER는 이미 선택된채이지만, REPOSITORY 데이터는 날라가게 된다. 그렇기 때문에, 이를 해결하기 위해서는 F5를 누르면 OWNER를 다시 선택할 수 있게 해야할 것 같다. 물론, REPOSITORY LIST의 데이터가 날아가지 않게 하기 위해서 PERSIST RECOIL을 사용할 수 있으나 이는 레포를 다시 선택하게 하는데에 있어서 문제가 생길 여지가 있어서 여러 사항을 유의하여 만들어야 할 것이다!

### Reproduction URL

.

### Reproduction Steps

```bash
.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by bentshrimp** [comment]
duplicate of #175
