### ISSUE TITLE
🚀 [REQUEST] - SEO work

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_client#51]
### Describe

setting SEO works to search Open-Set-Go

### Reasons

We get our page by searching the whole url, "www.open-set-go.com" only.

### Additional Explanation

[This Indian bro](https://www.youtube.com/watch?v=j8OUmE4Vj3M&ab_channel=codedamn) explains about SEO for react app insanely well.

### Connection

- [X] Have no effect on other functions
- [ ] Other functions need to be changed

**Comment by bentshrimp** [comment]
The situation will be way better by just changing title from "React App" to "Open-Set-Go". #65
