### ISSUE TITLE
🚀 [REQUEST] - Meta Data

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_client#65]
### Describe

As shown in the picture below, the current logo and the name that is open to the outside seem to be included as the react default. There will need to be a correction in that area.
밑의 사진과 같이 현재 로고와 외부에 공개되는 이름이 react 기본값으로 들어가있는것 같다. 해당 부분에 있어서 수정을 해야할 것이다.

![image](https://github.com/AgainIoT/Open-Set-Go_client/assets/77202633/4cb082b3-4033-4905-a7cc-79a2de4ae156)

### Reasons

It seems to have a big impact when people try to access the site.
사람들이 해당 사이트를 접근하려고 할때 큰 영향을 미칠 것으로 보인다.

### Connection

- [X] Have no effect on other functions
- [ ] Other functions need to be changed

**Comment by bentshrimp** [comment]
Should the title be "Open Set Go"? or "Open-Set-Go"?

**Comment by ymw0407** [comment]
I think ... Open-Set-Go is better. But this also seems to be a topic to talk about. Please take a look at the opinions of other maintainers.나는... Open-Set-Go가 더 좋다고 생각한다. 하지만 이 또한 얘기해볼만한 주제인 것 같다. 다른 maintainer들의 의견은 어떠한지 의견 한번씩 부탁한다.
@AgainIoT/development-team

**Comment by ymw0407** [comment]
I think it's a good idea to do it with Open-Set-Go.
우선은 Open-Set-Go로 해보는게 좋을 것 같습니다.

**Comment by bentshrimp** [comment]
roger that
