### ISSUE TITLE
🚀 [REQUEST] - 404 page need!

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_client#66]
### Describe

Currently, 404 pages do not exist separately, but I think we need to make 404 pages and supplement them both in terms of security and completeness.
현재는 404 페이지가 따로 존재하지 않는데 404페이지를 만들어서 보안적으로나 완성도의 차원에서나 보완을 해야할 것 같습니다.

### Reasons

I'm replacing it all in the above ^\~^
위의 내용에서 모두 대체하고 있습니다 ^\~^

### Connection

- [X] Have no effect on other functions
- [ ] Other functions need to be changed

**Comment by bentshrimp** [comment]
what about 500 pages? I think we also need that.
