### ISSUE TITLE
🚀 [REQUEST] - Improving Issue Template

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_client#68]
### Describe

Adding New Issue Template for maintainers & Improve overall Issue Templates
maintainer들을 위한 새로운 Issue Template 추가하기 & 전반적인 Issue Template들 개선

### Reasons

I'm currently using three Issue Template, but it seems that there is something to be supplemented after using it so far. We will improve the Issue Template accordingly.
Issue Template을 현재 3가지 사용하고 있는데, 지금까지 사용해본 결과 보완할 점이 있어보인다. 이에 맞추어 Issue Template을 개선해볼 것이다.

### Additional Explanation

Please comment on this like "Some parts don't seem necessary"! It's even better if you contribute yourself!
이와 관련하여 "어떤 부분은 필요가 없는 것 같다"와 같은 의견을 comment로 제시해주세요! 직접 기여해주시면 더 좋습니다!

Please note that it's being done in the following way on the server side!
Server 쪽에서는 다음과 같은 방식으로 진행되고 있으니까 참고해주셔도 좋습니다!

https://github.com/AgainIoT/Open-Set-Go_server/issues/95

### Connection

- [X] Have no effect on other functions
- [ ] Other functions need to be changed

**Comment by ancy0** [comment]
In addition to the current template, it would be nice to add a template that suggest something that needs to be refactored.
I think adding features and refactoring are separate tasks.
However, suggests about refactoring are also currently using a Feature Request template.

현재 템플릿 외에 리팩토링이 필요한 것을 제안하는 템플릿을 추가하면 좋을 것 같습니다.
기능 추가와 리팩토링은 별개의 작업이라고 생각합니다.
그러나 리팩토링에 대한 제안도 현재 Feature Request 템플릿을 사용하고 있습니다.
